version: "3.2"

services:
  redcomexpress:
    container_name: redcomexpress
    restart: always
    build: .
    ports:
      - "3333:3333"
    links:
      - "mongo"

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"